apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mdb-azure-disk
  resources:
    requests:
      storage: 10Gi # Adjust the storage size as needed
