apiVersion: v1
kind: Secret
metadata:
  name: secret-wp
stringData:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_PASSWORD: password
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wordpress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wp-statefulset
spec:
  serviceName: wp-statefulset
  replicas: 1
  selector:
    matchLabels:
      #app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        role: wp
       # app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wp-container
        image: wordpress:php8.2-apache
        env:
            - name: WORDPRESS_DB_HOST
              valueFrom: 
                 secretKeyRef:
                   name: secret-wp
                   key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_PASSWORD
              valueFrom: 
                  secretKeyRef:
                    name: secret-wp
                    key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_USER
              valueFrom: 
                    secretKeyRef:
                      name: secret-wp
                      key: WORDPRESS_DB_USER         
            - name: WORDPRESS_DB_NAME
              valueFrom: 
                      secretKeyRef:
                        name: secret-wp
                        key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: wp-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: wp-azure-disk
      resources:
        requests:
          storage: 10Gi # Must match the PVC size
